In [80]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [81]:
nnfs.init()

In [82]:
X, y = spiral_data(100, 3)

In [83]:
class Layer_Dense:
    def __init__(self, N_inp, N_neurons):
        self.weights = 0.10 * np.random.randn(N_inp, N_neurons)
        self.biases = np.zeros((1, N_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
class ReLU_Activation:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
class Softmax_Activation:
    def forward(self, inputs):
        exp_val = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_val / np.sum(exp_val, axis=1, keepdims=True)
        self.output = probabilities
class Loss:
    def calc_loss(self, output, y):
        losses = self.forward(output, y)
        batch_loss = np.mean(losses)
        return batch_loss
class CategoricalCrossEntropy_Loss(Loss):
    def forward(self, y_pred, y_true):
        sample = len(y_pred)
        y_pred_clip = np.clip(y_pred, 1e-7, 1-1e-7)
        if len(y_true.shape) == 1:
            confidence = y_pred_clip[range(sample), y_true]
        elif len(y_true.shape) == 2:
            confidence = np.sum(y_pred_clip*y_true, axis=1)
        negative_log = -np.log(confidence)
        return negative_log
             

In [84]:
layer1 = Layer_Dense(2,3)
layer2 = Layer_Dense(3,3)
activation = ReLU_Activation()
softmax = Softmax_Activation()

In [85]:
layer1.forward(X)
print(layer1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.04751880e-03  1.13953615e-03 -4.79835027e-04]
 [-2.74148444e-03  3.17291520e-03 -8.69217969e-04]
 [-4.21883678e-03  5.26662590e-03 -5.59126842e-04]
 [-5.77076850e-03  7.14014098e-03 -8.94304423e-04]
 [-3.54307005e-03  3.50254891e-03 -2.33634817e-03]
 [-8.92670080e-03  1.07678771e-02 -1.94532378e-03]
 [-9.33507830e-03  1.07238032e-02 -3.12273996e-03]
 [-1.12437597e-02  1.31128011e-02 -3.36296740e-03]
 [-1.33869564e-02  1.62009075e-02 -2.81017949e-03]
 [-1.48779741e-02  1.79484244e-02 -3.23859532e-03]
 [-1.20035885e-02  1.58119127e-02  8.65937036e-05]
 [-1.56528335e-02  1.99173335e-02 -1.30997354e-03]
 [-1.85718201e-02  2.30642669e-02 -2.70479405e-03]
 [-1.78093594e-02  2.27836706e-02 -1.24245719e-03]
 [-1.85300540e-02  2.38476787e-02 -1.00471661e-03]
 [-6.99865166e-03  1.11472746e-02  3.96097917e-03]
 [-2.19024289e-02  2.79446505e-02 -1.68075715e-03]
 [-1.69829167e-02  2.29598470e-02  1.31671689e-03]
 [-2.60229036e-02  3.27291936e-

In [86]:
activation.forward(layer1.output)
print(activation.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.13953615e-03 0.00000000e+00]
 [0.00000000e+00 3.17291520e-03 0.00000000e+00]
 [0.00000000e+00 5.26662590e-03 0.00000000e+00]
 [0.00000000e+00 7.14014098e-03 0.00000000e+00]
 [0.00000000e+00 3.50254891e-03 0.00000000e+00]
 [0.00000000e+00 1.07678771e-02 0.00000000e+00]
 [0.00000000e+00 1.07238032e-02 0.00000000e+00]
 [0.00000000e+00 1.31128011e-02 0.00000000e+00]
 [0.00000000e+00 1.62009075e-02 0.00000000e+00]
 [0.00000000e+00 1.79484244e-02 0.00000000e+00]
 [0.00000000e+00 1.58119127e-02 8.65937036e-05]
 [0.00000000e+00 1.99173335e-02 0.00000000e+00]
 [0.00000000e+00 2.30642669e-02 0.00000000e+00]
 [0.00000000e+00 2.27836706e-02 0.00000000e+00]
 [0.00000000e+00 2.38476787e-02 0.00000000e+00]
 [0.00000000e+00 1.11472746e-02 3.96097917e-03]
 [0.00000000e+00 2.79446505e-02 0.00000000e+00]
 [0.00000000e+00 2.29598470e-02 1.31671689e-03]
 [0.00000000e+00 3.27291936e-02 0.00000000e+00]
 [0.00000000e+00 3.25863250e-02 0.000000

In [87]:
# softmax.forward(layer1.output)
# print(softmax.output[-9:-1])


In [88]:
layer2.forward(activation.output)
softmax.forward(layer2.output)

In [89]:
loss_fn = CategoricalCrossEntropy_Loss()
loss_val = loss_fn.calc_loss(softmax.output, y)
print(loss_val)

1.098445
