In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [3]:
nnfs.init()

In [4]:
X, y = spiral_data(100, 3)

In [5]:
class Layer_Dense:
    def __init__(self, N_inp, N_neurons):
        self.weights = 0.10 * np.random.randn(N_inp, N_neurons)
        self.biases = np.zeros((1, N_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
class ReLU_Activation:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
class Softmax_Activation:
    def forward(self, inputs):
        exp_val = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_val / np.sum(exp_val, axis=1, keepdims=True)
        self.output = probabilities

In [6]:
layer1 = Layer_Dense(2,5)
activation = ReLU_Activation()
softmax = Softmax_Activation()

In [7]:
layer1.forward(X)
print(layer1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]


In [8]:
activation.forward(layer1.output)
print(activation.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [14]:
softmax.forward(layer1.output)
print(softmax.output[-9:-1])


[[0.21486449 0.1928398  0.21380122 0.19080003 0.18769446]
 [0.22132936 0.16841166 0.1928704  0.22411542 0.19327325]
 [0.21323602 0.19553752 0.21475674 0.18858369 0.18788606]
 [0.22362131 0.17882285 0.20872186 0.20257157 0.18626235]
 [0.22531301 0.16751446 0.19686787 0.22034551 0.18995914]
 [0.22665131 0.17169924 0.20382513 0.21100396 0.1868204 ]
 [0.22640921 0.16730027 0.1980198  0.21923856 0.18903221]
 [0.2270277  0.17196411 0.20467699 0.21000206 0.18632919]]
